((nil . ((indent-tabs-mode . nil)
         (tab-width . 2)
         (c-basic-offset . 2)
         (fill-column . 80)))
 (js-mode . ((indent-tabs-mode . nil)
			 (tab-width . 2)))
 (espresso-mode . ((indent-tabs-mode . nil)
				   (espresso-indent-level . 1)
				   (tab-width . 2)
				   (c-basic-offset . 2)))
