((nil . ((indent-tabs-mode . nil)
         (tab-width . 2)
         (c-basic-offset . 2)
         (fill-column . 80)))
 (c-mode . ((indent-tabs-mode . nil)
            (tab-width . 2)))
 (js-mode . ((indent-tabs-mode . nil)
             (js-indent-level . 2))))
