((nil . ((indent-tabs-mode . nil)
         (tab-width . 2)
         (c-basic-offset . 2)
         (fill-column . 80)))
 ;(c-mode . ((c-file-style . "BSD")))
 ;(c++-mode . ((c-file-style . "BSD")))
 )
