// -*- C++ -*-
// Copyright 2012, Evan Klitzke <evan@eklitzke.org>
//
// This file is AUTOGENERATED by gen_key_sources.py, do not edit by hand!

#ifndef SRC_KEYCODE_H_
#define SRC_KEYCODE_H_

#include <v8.h>
#include <string>
#include "./embeddable.h"

using v8::Arguments;
using v8::Handle;
using v8::Value;

namespace e {
class KeyCode: public Embeddable {
  public:
    explicit KeyCode(int code,
                     const std::string &short_name);
    explicit KeyCode(int code);
    const std::string& GetName(void) const;
    bool IsASCII(void) const;
    int GetCode(void) const;
    char GetChar(void) const;
    Handle<Value> ToScript();
  private:
    int code_;
    std::string short_name_;
};

namespace keycode {
const KeyCode& curses_code_to_keycode(int code);
}
}

#endif  // SRC_KEYCODE_H_
