// -*- C++ -*-
// Copyright 2012, Evan Klitzke <evan@eklitzke.org>
//
// This file is AUTOGENERATED by gen_key_sources.py, do not edit by hand!

#ifndef SRC_KEYCODE_H_
#define SRC_KEYCODE_H_

#include <string>

namespace e {
class KeyCode {
  private:
    int code_;
    std::string short_name_;
  public:
    explicit KeyCode(int code,
                     const std::string &short_name);
    explicit KeyCode(int code);
    const std::string& get_name(void) const;
    bool is_ascii(void) const;
    int get_code(void) const;
    char get_char(void) const;
};

namespace keycode {
const KeyCode& curses_code_to_keycode(int code);
}
}

#endif  // SRC_KEYCODE_H_
